version: "3.5"

services:
  postgres:
    container_name: mongodb
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb:
